# Generated by Django 4.2.13 on 2024-11-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=100, unique=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_limite', models.DateField()),
                ('ordem_apresentacao', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
